config/routes.rb
FoosballApp::Application.routes.draw do
  devise_for :players

  resources :players
  resources :games do
    post :generate_teams, on: :new
    post :player_dropdown, on: :new
    post :add_player, on: :new
    post :remove_player, on: :new
    post :setup_submit, on: :new
    member do 
      post :undo
      post :rematch
    end
    
  end

  resources :positions do
    member do
      post :score
    end
  end

  root 'pages#home'

end

app/models/game.rb
# == Schema Information
#
# Table name: games
#has_many :game_team
#  id         :integer          not null, primary key
#  created_at :datetime
#  updated_at :datetime
#

class Game < ActiveRecord::Base
	has_many :teams, :dependent => :destroy
	has_many :positions, :through => :teams
	has_many :players, :through => :positions
	has_many :goals, :through => :positions

	accepts_nested_attributes_for :teams, :allow_destroy => true
	
	enum color: [:red, :blue]

	scope :completed, -> { where.not(completed_at: nil) }

	validate :valid_if_two_teams

	#validators
	def valid_if_two_teams
		errors[:base] << "Games must include two teams." if teams.reject(&:marked_for_destruction?).count != 2
	end

	#Class Methods

	#builds new team based a passed in team. 
	#Shifts players one spot moving from goalie to striker
	private
	def self.shift_team(old_team)
		old_team_positions = old_team.positions.order(:position_type)
		new_team = Team.new
		if old_team.color == "red"
			new_team.color = "blue"
		else
			new_team.color = "red"
		end

		#Position.position_types.each do |position_key, position_value|
		4.times do |position_index|
 			position = new_team.positions.build
 			position.position_type = position_index

 			#shift players from goalie to striker. look at last game played
 			current_player_id = old_team_positions[position_index].player_id
 			l = (position_index-1)%4
 			found_teammate = false
 			while l != position_index
 				#puts "current_player_id:#{current_player_id} old_team_positions[l].player_id:#{old_team_positions[l].player_id}"
 				if current_player_id != old_team_positions[l].player_id
 					position.player_id = old_team_positions[l].player_id
 					found_teammate = true
 					break
 				end
 				l = (l-1)%4
 			end

 			#if no other player was found, means the entire team is the same player
 			if !found_teammate
 				position.player_id = current_player_id
 			end
 		end

 		return new_team
	end


	public
	def self.new_game
		game = self.new

 		#create the blue team
 		blueteam = Team.new_team(game)
 		blueteam.color = "blue"

 		#create the red team
 		redteam = Team.new_team(game)
 		redteam.color = "red"

 		return game
	end

	#Handles how we rematch games.
	#Teams rotate on table and each player is shifted a position over
	def self.new_rematch_game(previous_game)
 		previous_red_team = previous_game.teams.red.first
 		previous_blue_team = previous_game.teams.blue.first

 		rematch_game = Game.new

 		blue_team = Game.shift_team(previous_red_team)
 		red_team = Game.shift_team(previous_blue_team)

 		rematch_game.teams << [blue_team, red_team]

 		return rematch_game
	end

	#Instance Methods

	#Passed eligible players
	def generate_random_teams(players)

		#randomize
		players = players.shuffle

		assign_players_to_teams(players)
	end

	def assign_players_to_teams(players)
		players.each_with_index do |player, index|
			if(index.even?)
 				self.teams[0].add_pending_player( player )
 			else
 				self.teams[1].add_pending_player( player )
 			end
		end
	end

	def setup_submit

	end

	def winning_team
		self.teams.where(winner: true).first
	end

	def losing_team
		self.teams.where(winner: false).first
	end

	def undo_last_goal
		if self.completed_at != nil
			self.completed_at = nil
			self.teams.each do |team|
				team.winner = false
				team.save
			end
			self.save
		end

		lastgoal = self.goals.order("created_at").last
 		lastgoal.destroy
	end


	#the following methods have the potential to be moved into a decorator
	def is_finished
		if self.completed_at 
			true
		else
			false
		end
	end

	def is_in_progress
		if not self.completed_at 
			true
		else
			false
		end
	end

	#give player, returns true or false for if the player was on the winning team of the game
	def did_player_win?(player)
		winner_count = self.teams.winner.joins(:positions).where(:positions => {player_id: player.id}).count
		return winner_count > 0
	end

	def team(player)
		self.teams.joins(:positions).where(:positions => {player_id: player.id}).first
	end

	#goals scored by the passed in player
	def goals_scored(player)
		self.positions.where("positions.player_id = ?",player.id).joins(:goals).merge(Goal.scored_goal).count
	end
	
# def game_cannot_be_started_without_two_teams
#		if started_at != nil and teams.size < 2 
#			errors[:base] = 'Games cannot be started without two teams' 
#		end
#	end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

 	def index
 	end

 	def create
 		#todo: Need to whitelist parameters. Did this to get it working initially
 		@game = Game.new(game_params)
 		if @game.save
 			redirect_to edit_game_path(@game)
 		else
 			render :new
 		end
 	end

 	def new
 		#all of this will be moved to a service object or in the model. Refactored soon
 		@game = Game.new_game
 		@players = Player.all.order(:firstname)

 		@blue_team_players = Player.all.order(:firstname)
 		@red_team_players = Player.all.order(:firstname)

 	end

 	def edit
 		#@game = Game.includes(teams: [positions: [:goals]]).order("teams.color, positions.position_type desc").find(params[:id])

 		@game = Game.includes(teams: [positions: [goals: [:player]]]).find(params[:id]).decorate
 		@redteam = @game.teams.red.first
 		@blueteam = @game.teams.blue.first
 		@positions = Position.position_types
 	end

 	def show
 	end

 	def update
 	end

 	def destroy
 		game = Game.find(params[:id])

 		if game.destroy then 
 			redirect_to games_path
 		else
 			redirect_to games_path, flash: {error: "Something went wrong. Please try again"}
 		end
 	end

 	def undo
 		game = Game.find_by_id(undo_params[:id])
 		game.undo_last_goal
 		redirect_to edit_game_path(game)
 	end

 	def index
 		@games = GameDecorator.decorate_collection(Game.order("created_at desc").paginate(:page => params[:page], :per_page => 10))
 	end

 	def rematch
 		#all of this will be moved to a service object or in the model. Refactored soon
 		#need to whitelist params
 		previous_game = Game.includes(teams: [:positions]).find_by_id(params[:id])

 		@game = Game.new_rematch_game(previous_game)

 		@players = Player.all.order(:firstname)

 		@blue_team_players = Player.all.order(:firstname)
 		@red_team_players = Player.all.order(:firstname)

 		render :action => :new
 	end

 	def add_player
 		selected_players = Player.find(setup_params[:player_id])

		selected_players_id = selected_players.map(&:id)
 		available_players = Player.where.not(id: selected_players_id)

 		render partial: "setup_game_modal", locals: { selected_players: selected_players, available_players: available_players, game: nil }
 	end

 	def remove_player
 		player_ids = setup_params[:player_id]
 		#remove player id from selected list
 		player_ids.delete(setup_params[:remove_id])

 		selected_players = Player.find(player_ids)
 		
 		selected_players_id = selected_players.map(&:id)
 		available_players = Player.where.not(id: selected_players_id)

 		render partial: "setup_game_modal", locals: { selected_players: selected_players, available_players: available_players, game: nil }
 	end

 	def player_dropdown
 		selected_players_id = setup_params[:selected_players_id]
 		if selected_players_id == nil
 			selected_players_id = []
 		end

 		if setup_params[:commit] == "Add Player"
 			selected_players_id << setup_params[:add_id]
 		elsif setup_params[:commit] == "Remove Player"
 			if setup_params[:remove_player_id]
 				selected_players_id.delete(setup_params[:remove_player_id])
 			end
 		end

		selected_players = Player.find(selected_players_id)

 		available_players = Player.where.not(id: selected_players_id)

 		render partial: "player_list", locals: { selected_players: selected_players, available_players: available_players } 
 	end

 	#need to move this to model or service object
 	def generate_teams
 		#seems redundant..just want to make sure I have actual players. Could remove this and stick with what is passed in player_id params
 		selected_players = Player.find(setup_params[:player_id])
 		selected_players_id = selected_players.map(&:id)
 		available_players = Player.where.not(id: selected_players_id)

 		game = Game.new_game
 		game.generate_random_teams(selected_players);

 		render partial: "setup_game_modal", locals: { selected_players: selected_players, available_players: available_players, game: game}
 	end

 	def setup_submit
 		@game = Game.new_game

 		@players = Player.all.order(:firstname)

 		@blue_team_players = Player.find(setup_params[:blue_team])
 		@red_team_players = Player.find(setup_params[:red_team])

 		render :new
 	end

 	private
	  def game_params
	    params.require(:game).permit( :id, :teams_attributes => [:id, :color, :positions_attributes => [:id, :player_id, :position_type]])
	  end

	  def undo_params
	  	params.permit(:id)
	  end

	  def setup_params
	  	params.permit(:id, :commit, :remove_player_id, :remove_id, :add_id, :player_id => [], :blue_team => [], :red_team => [])
	  end
end

app/helpers/game_helper.rb
module GameHelper
end

app/views/games/_modal_player_list.html.erb
<ul class="list-group">
  <% selected_players.each do |player| %>
		<li class="list-group-item">
			<%= form_tag(remove_player_new_game_path,id: "form_remove_player", remote: true) do %>
				<%= hidden_field_tag "remove_id", player.id %>
				<% selected_players.each do |input_player| %>
					<%= hidden_field_tag "player_id[]", input_player.id %>
				<% end %>
				<button type="submit" class="btn btn-default" aria-label="Remove Player">
				  <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
				</button>
	    	<strong><%= player.firstname.humanize %>,<%= player.lastname.humanize %></strong>
	    <% end %>
    </li>
	 <% end %>

</ul>

app/views/games/_position_row.html.erb
<div class="position-row">
  <div class="column">
    <% if red_position.goals.own_goal.count > 0 then %>
      <span class="badge alert-danger"><%= red_position.goals.own_goal.count %></span>
    <% end %>
    <% if red_position.goals.scored_goal.count > 0 then %>
      <span class="badge alert-success"><%= red_position.goals.scored_goal.count %></span>
    <% end %>
  </div>
  <div class="left column">
    <%= button_to "Goal", score_position_path( red_position ), class: "btn btn-default bold", style: "font-weight:bold;"%>
  </div>
  <div class="center column"><strong><%= position %></strong></div>
  <div class="right column">
    <%= button_to "Goal", score_position_path( blue_position ), class: "btn btn-default bold", style: "font-weight:bold;"%>
  </div>
  <div class="column">
    <% if blue_position.goals.own_goal.count > 0 then %>
      <span class="badge alert-danger"><%= blue_position.goals.own_goal.count %></span>
    <% end %>
    <% if blue_position.goals.scored_goal.count > 0 then %>
      <span class="badge alert-success"><%= blue_position.goals.scored_goal.count %></span>
    <% end %>
  </div>
</div>

app/views/games/_position_row_tr.html.erb
<tr class="position-row">
  <td>
    <% if red_position.goals.count > 0 then %>
      <% red_position.goals.scored_goal.count.times do %>
        <%= fa_icon('futbol-o', class: "pull-right") %>
      <% end %>

      <% red_position.goals.own_goal.count.times do %>
        <%= fa_icon('futbol-o', style: "color:red;", class: "pull-right") %>
      <% end %>
    <% end %>
    
  </td>
  <td>
    <% if not game.completed? %>
      <%= form_tag(score_position_path( red_position ), class: "form-goal-scored") do %>
        <input type="hidden" name="quantity" value="1"/>
        <%= submit_tag 'Goal',class: "btn btn-default bold", style: "font-weight:bold;" %>
      <% end %>
    <% else %>
      <strong><%= red_position.player.username.humanize %></strong>
    <% end %>
  </td>
  <td style="font-weight:bold;"><small style="color: #777;"><%= position %></small></td>
  <td>
    <% if not game.completed? %>
      <%= form_tag(score_position_path( blue_position ), class: "form-goal-scored") do %>
        <input type="hidden" name="quantity" value="1"/>
        <%= submit_tag 'Goal',class: "btn btn-default bold", style: "font-weight:bold;" %>
      <% end %>
    <% else %>
      <strong><%= blue_position.player.username.humanize %></strong>
    <% end %>
  </td>
  <td>
    <% if blue_position.goals.count > 0 then %>
      <% blue_position.goals.scored_goal.count.times do %>
        <%= fa_icon('futbol-o', class: "pull-left") %>
      <% end %>
      
      <% blue_position.goals.own_goal.count.times do %>
        <%= fa_icon('futbol-o', style: "color:red;", class: "pull-left") %>
      <% end %>
    <% end %>
  </td>
</tr>

app/views/games/_setup_game_modal.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <h4 class="modal-title" id="modal-label">Select the Competitors!</h4>
</div>
<div class="modal-body">         
  <div class="container-fluid">
  	<%= form_tag(add_player_new_game_path, id: "form_add_player", remote: true) do %>

    	<% selected_players.each do |player| %>
    		<%= hidden_field_tag "player_id[]", player.id, {id: nil} %>
    	<% end %>

    	<div class="panel panel-default">
  			<div class="panel-body">
			    <div class="row">
			    	<div class="col-xs-6">
			    		<%= select_tag "player_id[]", 
			    					options_for_select(available_players.collect{|player| ["#{player.firstname.humanize}, #{player.lastname.humanize}", player.id]}), id: nil, class: "form-control" %>
			    	</div>
			    	<div class="col-xs-6">
							<%= submit_tag 'Add Player', class: "btn btn-large btn-default add-player-button", "data-loading-text" => "Adding Player..." %>
			    	</div>
					</div>
				</div>
			</div>
		<% end %>

    <%= render partial: "modal_player_list", locals: { selected_players: selected_players } %>

	  <% if game != nil %>
	  	<div class="panel panel-default">
	  		<div class="panel-heading">
	        <h5><strong>Generated Teams</strong></h5>
	      </div>
	  		<div class="panel-body">
			  	<% game.teams.each_with_index do |team, index| %>
			  		<% if index == 1 %>
			  			<strong>Versus</strong>
			  		<% end %>
			  		<span class="<%= team.color %>-font"><strong><%= team.pending_players.map(&:username).map{|s| s.humanize()}.join(", ") %></strong></span>
			  	<% end %>
			  </div>
		  </div>
		<% end %>
	</div> 
</div>
<div class="modal-footer">
  <%= form_tag(generate_teams_new_game_path, id: "form_generate_teams", remote: true, class: "pull-right") do %>
    <% selected_players.each do |player| %>
      <%= hidden_field_tag "player_id[]", player.id %>
    <% end %>
    <%= button_tag 'Generate Teams', :type => "submit", :name => 'submit_button', class: "btn btn-large btn-primary generate-teams-button", "data-loading-text" => "Loading..." %>
  <% end %>

  <% if game != nil %>
		<%= form_tag(setup_submit_new_game_path, id: "submit-setup-form", class: "pull-right") do %>
	    <% game.teams.each_with_index do |team, index| %>
	    	<% if team.color =="blue" %>
	    		<% team.pending_players.each do |player| %>
	    			<%= hidden_field_tag "blue_team[]", player.id, {id: nil} %>
	    		<% end %>
	    	<% else %>
	    		<% team.pending_players.each do |player| %>
	    			<%= hidden_field_tag "red_team[]", player.id, {id: nil} %>
	    		<% end %>
	    	<% end %>
	    <% end %>
	    <%= button_tag 'Lets Go!', :type => "submit", :name => 'submit_button', class: "btn btn-large btn-primary generate-teams-button", "data-loading-text" => "Loading..." %>
	  <% end %>
	<% end %>
</div>

app/views/games/edit.html.erb
<%= stylesheet_link_tag "games", :media => "all" %>
<script>
  $(document).ready(function(){
    $(".form-goal-scored").on("submit", function(eo){
      var $form = $(eo.currentTarget);
      var $checkbox_own_goal = $("#checkbox-own-goal");

      if( $checkbox_own_goal.is(":checked") ){
        $form[0].quantity.value = $("#checkbox-own-goal").val();
      }
    });
  });
</script>
<center>
  <div class="div-foos-title"/>
    <h1 class="foos">Game View</h1>
    <div class="break"></div>
  </div>

  <% if @game.completed_at? %>
    <div class="alert alert-info alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <strong><%= @game.winning_team_color %> Won!</strong> - Completed at:<%= @game.completed_at.to_s %>
    </div>

    <% if player_signed_in? %>
      <div class="btn-group">
        <%= form_for @game, url:{action: "rematch"}, html:{method: "post"} do |f| %>
          <%= f.submit("Rematch", :class => 'btn btn-default btn-sm') %>
        <% end %>
      </div>
    <% end %>
  <% end %>

  <br>
  <br>


  <div class="panel panel-default">
    <div class="panel-heading">
      <h5><strong>Scoreboard</strong></h5>
    </div>
    <div class="panel-body panel-overflow-x">
      <% if player_signed_in? %>
        <%= button_to "Undo Goal", undo_game_path(@game), class: "btn btn-default btn-sm", style: "margin: .5em; font-weight:bold;" %>
      <% end %>

      <table class="panel scoreboard">

        <tr class="header">
          <td class="red-team-column" colspan="2">
              <strong class="red-font">Team Red</strong>
              <span class="glyphicon glyphicon-user red-font" aria-hidden="true" style="font-size: 18px;"></span>
          </td>
          <td class="score-column">
              <strong style="font-size: 1.6em;color: rgb(51,51,51);line-height: 1.5em; white-space: nowrap;"><%= @redteam.get_goals_total %> - <%= @blueteam.get_goals_total %></strong>
          </td>
          <td class="blue-team-column" colspan="2">
              <span class="glyphicon glyphicon-user blue-font" aria-hidden="true" style="font-size: 18px;"></span>
              <strong class="blue-font">Team Blue</strong>
          </td>
        </tr><!-- end header -->
        <tr>
          <td colspan="5" style="text-align:center;">
              <label for="checkbox-own-goal"><small>Own Goal:</small></label>
              <input type="checkbox" id="checkbox-own-goal" name="quantity" value="-1"/>
          </td>
        </tr>

        <%= render :partial => 'position_row_tr', :locals => { :position => 'Striker', :red_position => @game.teams.red.first.positions.striker, :blue_position => @game.teams.blue.first.positions.striker, :game => @game } %>
        <%= render :partial => 'position_row_tr', :locals => { :position => 'Midfield', :red_position => @game.teams.red.first.positions.midfield, :blue_position => @game.teams.blue.first.positions.midfield, :game => @game } %>
        <%= render :partial => 'position_row_tr', :locals => { :position => 'Defense', :red_position => @game.teams.red.first.positions.defense, :blue_position => @game.teams.blue.first.positions.defense, :game => @game } %>
        <%= render :partial => 'position_row_tr', :locals => { :position => 'Goalie', :red_position => @game.teams.red.first.positions.goalie, :blue_position => @game.teams.blue.first.positions.goalie, :game => @game } %>
      </table>
    </div>

  </div>
   
  

  <% if @game.has_goals? then %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h5><strong>Goals Scored</strong></h5>
      </div>
      <div class="panel-body panel-overflow-x">
        <span style="width:auto;">
          <table class="table table-hover table-condensed" style="width:auto;">
            <thead>
              <tr>
                <td><strong>Goal #</strong></td>
                <td><strong>Player</strong></td>
                <td><strong>Scored At</strong></td>
                <td class="blueteam"><strong>Blue</strong></td>
                <td class="redteam"><strong>Red</strong></td>
                <td><strong>Type</strong></td>
              </tr>
            </thead>
            <tbody>
              <% @game.goals_ordered.each_with_index do |goal, index| %>
                <tr>
                  <td><%= (index+1) %></td>
                  <td><%= goal.player.firstname.humanize %></td>
                  <td><%= goal.created_at %></td>
                  <td class="<%= "info" if goal.blue_goal? %>"><%= @game.teams.blue.first.get_team_score_at(goal) %></td>
                  <td class="<%= "info" if goal.red_goal?  %>"><%= @game.teams.red.first.get_team_score_at(goal) %></td>
                  <td class="<%= "danger" if goal.own_goal? %>">
                  <% if goal.own_goal? %>
                    (Own Goal)
                  <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </span>
      </div>
    </div>
  <% end %>
</center>

app/views/games/index.html.erb
<center>
  

  <div class="div-foos-title">
    <h1 class="foos">Games</h1>
    <div class="break"></div>
  </div>
  <% if player_signed_in? %>
    <%= link_to "Start a Game", new_game_path, class: "btn btn-large btn-primary" %>
  <% end %>
  <br>
  <%= will_paginate @games, renderer: BootstrapPagination::Rails %>
  <table class="table table-hover table-condensed">
    <thead>
      <tr>
        <th></th>
        <th>Completed At</th>
        <th>Winner</th>
      </tr>
    </thead>
    <tbody>
      <% @games.each do |game| %>
        <tr>
          <td>
              <% if player_signed_in? && current_player.admin? %>
                <%= link_to "Delete", game_path(game), :method => "delete", :class => 'btn btn-default btn-sm' %>
              <% end %>
              <%= link_to "View Game", edit_game_path(game), :method => "get", :class => 'btn btn-default btn-sm' %>

          </td>
          <td><%= game.completed_at %></td>
          <td>
            <% if game.completed? %>
              <span class="badge <%= game.winning_team_class %>">
                <%= game.winning_team_color %>
              </span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</center>

app/views/games/new.html.erb
<%= link_to "Setup Game", '#' , class: "btn btn-large btn-default", data: { :toggle => "modal", :target => "#modal-playerpicker"} %>
<br>
<br>
<%= form_for @game, url:{action: "create"}, html:{method: "post", class: "form-horizontal"} do |f| %>
    

    <%= f.hidden_field :id %>
    <%= f.fields_for :teams do |team_builder| %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"> 
            <strong class="<%= team_builder.object.color%>-font">Team <%= team_builder.object.color.humanize %></strong>
          </h3>
        </div>
        <div class="panel-body">
          <%= team_builder.hidden_field :color %>
          <div class="container-fluid">
            <%= team_builder.fields_for :positions do |position_builder| %>
              <div class="form-group">
                <div class="col-sm-1">
                  <label><%= position_builder.object.position_type.humanize%></label>
                </div>
                <div class="col-sm-5">
                  <%= position_builder.hidden_field :position_type %>
                  <% if team_builder.object.color == "blue" %>
                    <%= position_builder.select(:player_id, options_for_select(@blue_team_players.collect {|player| [player.firstname.humanize, player.id]}, position_builder.object.player_id), {}, {class: "form-control"}) %>
                  <% else %>
                    <%= position_builder.select(:player_id, options_for_select(@red_team_players.collect {|player| [player.firstname.humanize, player.id]}, position_builder.object.player_id), {}, {class: "form-control"}) %>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>


  <%=  f.submit("Start Game!", :class => 'btn btn-primary btn-sm') %>
  <br>
  <br>
<% end %>


<!-- Team GeneratorModal -->
<div class="modal fade" id="modal-playerpicker" tabindex="-1" role="dialog" aria-labelledby="modal-label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content" id="modal-content"> 
      <%= render "setup_game_modal", selected_players: [], available_players: @players, game: nil  %>
    </div>
  </div>
</div>