config/routes.rb
FoosballApp::Application.routes.draw do
  devise_for :players

  resources :players
  resources :games do
    post :generate_teams, on: :new
    post :player_dropdown, on: :new
    post :add_player, on: :new
    post :remove_player, on: :new
    post :setup_submit, on: :new
    member do 
      post :undo
      post :rematch
    end
    
  end

  resources :positions do
    member do
      post :score
    end
  end

  root 'pages#home'

end

app/models/player.rb
# == Schema Information
#
# Table name: players
#
#  id         :integer          not null, primary key
#  firstname  :string(255)
#  lastname   :string(255)
#  created_at :datetime
#  updated_at :datetime
#  username   :string(255)
#

class Player < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:username]
	has_many :positions
	has_many :goals

	validates :username, presence: true, 
						 length: { minimum: 4 }
	validates :firstname, presence: true
	validates :lastname, presence: true

	#subtracts own goals
	def total_goals
		return @total_goals if defined? @total_goals

		scored_goals = my_goals.merge(Goal.scored_goal).count
		own_goals = my_goals.merge(Goal.own_goal).count

		
		@total_goals ||= (scored_goals - own_goals)
	end

	def player_games
		@player_games ||= Game.uniq.completed.joins(:teams).joins(:positions).where("teams.id = positions.team_id").where(:positions => {:player_id => self.id})
	end

	def goals_per_game
		return 0 if my_completed_games.count == 0
		(total_goals*1.0)/my_completed_games.count
	end

	def goals_per_stick
		total_positions = self.positions.joins(:team => :game).merge(Game.completed).count

		if total_positions > 0
			(total_goals*1.0)/total_positions
		else
			0
		end
	end

	def editable?
  	return player_signed_in? && (current_player.admin? || current_player.id == self.id)
  end

	def player_wins
		@player_wins ||= completed_teams.merge(Team.winner).count
	end

	def player_losses
		@player_losses ||= completed_teams.merge(Team.loser).count
	end

	def win_percentage
		return 0 if my_completed_games.count == 0
		((player_wins*1.0)/my_completed_games.count)*100
	end

	def my_completed_games
		return @my_completed_games if defined? @my_completed_games

		@my_completed_games ||= Game.uniq.completed.joins(:teams).joins(:positions).where(:positions => {player_id: self.id})
	end

	#teams on completed games
	def completed_teams
		return @completed_teams if defined? @completed_teams
		@completed_teams ||= Team.uniq.joins(:positions).where(:positions => {:player_id => self.id}).joins(:game).merge(Game.completed)
	end

	def my_goals 
		return @my_goals if defined? @my_goals
		@my_goals ||= Goal.joins(:position => {:team => :game}).where(:positions => {player_id: self.id}).merge(Game.completed)
	end

	def plus_minus
		return @plus_minus if defined? @plus_minus

		opposing_teams = Team.joins(:game).where(:games => {id: my_completed_games}).where.not(:teams => {id: completed_teams}).uniq

		completed_teams_scored_goals = Goal.scored_goal.joins(:position => :team).where(:teams => {id: completed_teams}).count
		completed_teams_own_goals = Goal.own_goal.joins(:position => :team).where(:teams => {id: completed_teams}).count

		opposing_teams_scored_goals = Goal.scored_goal.joins(:position => :team).where(:teams => {id: opposing_teams}).count
		opposing_teams_own_goals = Goal.own_goal.joins(:position => :team).where(:teams => {id: opposing_teams}).count

		@plus_minus ||= completed_teams_scored_goals + opposing_teams_own_goals - opposing_teams_scored_goals - completed_teams_own_goals
	end

	def margin
		return 0 if my_completed_games.count == 0

		(plus_minus*1.0)/my_completed_games.count

	end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def new
  	@player = Player.new
  end

	def index
		@players = Player.all
	end

  def create
  	@player = Player.new(player_params).decorate
 
  	#if @player.save
		#	format.html { redirect_to edit_player_path(@player), notice: 'Player created successfully.' }
		#	format.json { render json: @player }
		#	format.js { render action: "show", status: :created, location: @player}
		#else
		#	format.html { redirect_to edit_player_path(@player), notice: 'Player created successfully.' }
		#end

		if @player.save
			flash[:notice] = "Player created."
			redirect_to edit_player_path(@player)
		else
			render :new
		end
	end

	def update
		@player = Player.find(params[:id])
		if @player.update(player_params)
			flash[:notice] = "Player saved."
			redirect_to edit_player_path(@player)
		else
			redirect_to edit_player_path(@player)
		end	
	end

	#need to move this logic into a helper or module to store statistics....or just a controller
  def edit
    @player = Player.find(params[:id]).decorate

    @games = GameDecorator.decorate_collection( Game.completed.distinct.joins(:teams).joins(:positions).where(:positions => {player_id: @player.id}).order(created_at: :desc).paginate(:page => params[:page], :per_page => 10) )
    game_ids = @games.map(&:id)

    @loser_ten = Team.distinct.loser.joins(:positions).where(:positions => {player_id: @player.id}, :teams => {game_id: game_ids}).count
    @winner_ten = Team.distinct.winner.joins(:positions).where(:positions => {player_id: @player.id}, :teams => {game_id: game_ids}).count
  end

  def show
  	@player = Player.find(params[:id])
  end

  private
	  def player_params
	    params.require(:player).permit(:username, :firstname, :lastname, :email)
	  end

end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<div class="form-group">
  <%= form.label :username, 'User Name' %><br>
  <%= form.text_field :username, class: "form-control", placeholder: 'user name', :disabled => !player.editable? %>
</div>

<div class="form-group">
  <%= form.label :firstname, 'First Name' %><br>
  <%= form.text_field :firstname, class: "form-control", placeholder: 'first name', :disabled => !player.editable? %>
</div>

<div class="form-group">
  <%= form.label :lastname, 'Last Name' %><br>
  <%= form.text_field :lastname, class: "form-control", placeholder: 'last name', :disabled => !player.editable? %>
</div>

<div class="form-group">
  <%= form.label :email, 'Email' %><br>
  <%= form.text_field :email, class: "form-control", placeholder: 'email address', :disabled => !player.editable? %>
</div>

app/views/players/edit.html.erb
<%= stylesheet_link_tag    "players", :media => "all" %>
<%= button_to "Back", players_path, :method => "get", :class => 'btn btn-default btn-sm' %>
<center>
  <div class="div-foos-title">
    <h1 class="foos">Player View</h1>
    <div class="break"></div>
  </div>
</center>
<div class="panel panel-default">
  <div class="panel-heading"><h5><strong>Player Form</strong></h5></div>
  <div class="panel-body">
    <%= form_for @player, url: player_path(@player), method: :patch do |f| %>

      <% if @player.errors.any? %>
        <div id="error_explanation">
          <ul>
            <% @player.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= render :partial => 'form', :locals => { :form => f, :player => @player } %>

      <% if @player.editable? %>
        <div class="form-group">
          <%= f.submit "Update Player", class: 'btn btn-primary btn-sm'%>
        </div>
        <% if @player.current_player? %>
          <div class="form-group">
            <%= link_to "Update Password", edit_player_registration_path(@player), class: 'btn btn-default btn-sm' %>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

<% if @player.persisted? %>
  <div class="panel panel-default">
    <div class="panel-heading"><h5><strong>Player Stats</strong></h5></div>
    <div class="panel-body panel-overflow-x">
      <ul>
        <li><b>Goals Scored:</b> <%= @player.total_goals %></li>
        <li><b>Win Percentage:</b> <%= @player.win_percentage.to_i %></li>
        <li><b>Record:</b> <%= @player.player_wins %> - <%= @player.player_losses %>
        <li><b>Goals Per Game:</b> <%= number_with_precision(@player.goals_per_game, precision: 2) %>
        <li><b>Goals Per Position:</b> <%= number_with_precision(@player.goals_per_stick, precision: 2) %>
        <li><b>Plus/Minus Rating:</b> <%= @player.plus_minus %>
      </ul>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading"><h5><strong>Game Logs</strong></h5></div>
    <div class="panel-body panel-overflow-x">
      <% if @games.count > 0 then %>
        <b>Record Last <%= @games.count %> Games:</b> <%= @winner_ten %> - <%= @loser_ten %><br>
        <%= will_paginate @games, renderer: BootstrapPagination::Rails %>
        <table class="table table-hover table-condensed" style="width:auto;">
          <thead>
            <tr>
              <th>Game ID</th>
              <th>Completed At</th>
              <th>W/L</th>
              <th>Score</th>
              <th>Teammates</th>
              <th>Opposing Team</th>
              <th>Goals Scored</th>
            </tr>
          </thead>
          <tbody>
          <% @games.each do |game| %>
            <tr>
              <td><%= button_to "View Game", edit_game_path(game), :method => "get", :class => 'btn btn-default btn-sm' %></td>
              <td><%= game.completed_at %></td>
              <td>
                <%= game.badge_players_game_result(@player) %>  
              </td>
              <td>
                <%= game.team(@player).get_goals_total %> - <%= game.team(@player).opposing_team.get_goals_total %>
              </td>
              <td><%= game.team(@player).players_list %></td>
              <td><%= game.team(@player).opposing_team.players_list %></td>
              <td><%= game.goals_scored(@player) %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      <% else %>
        <b>No games played yet...</b>
      <% end %>
    </div>
  </div>
<% end %>



    



app/views/players/index.html.erb
<div class="div-foos-title">
  <center>
    <h1 class="foos">Players</h1>
    <div class="break"></div>
  </center>
</div>
<table class="table table-hover table-condensed">
	<thead>
		<tr>
			<th></th>
			<th>User Name</th>
			<th>First Name</th>
			<th>Last Name</th>
		</tr>
	</thead>
	<tbody>
	<% @players.each do |player| %>
		<tr>
			<td>
				<%= button_to "View Player", edit_player_path(player), :method => "get", :class => 'btn btn-default btn-sm' %>
			</td>
			<td><%= player.username %></td>
			<td><%= player.firstname.humanize %></td>
			<td><%= player.lastname.humanize %></td>
		</tr>
	<% end %>
	</tbody>
</table>

app/views/players/new.html.erb
<%= form_for @player, url: players_path do |f| %>

	<% if @player.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@player.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @player.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :username, 'User Name' %><br>
    <%= f.text_field :username %>
  </div>

  <div class="form-group">
    <%= f.label :firstname, 'First Name' %><br>
    <%= f.text_field :firstname %>
  </div>

  <div class="form-group">
    <%= f.label :lastname, 'Last Name' %><br>
    <%= f.text_field :lastname %>
  </div>
 
 
  <div class="form-group">
    <%= f.submit "Save Player", class: 'btn btn-default btn-sm'%>
  </div>
<% end %>




<!--<form role="form">
  <div class="form-group">
    <label for="firstName">First Name</label>
    <input type="text" class="form-control" id="firstName" placeholder="Enter First Name">
  </div>
  <div class="form-group">
    <label for="lastName">Last Name</label>
    <input type="text" class="form-control" id="lastName" placeholder="Enter Last Name">
  </div>
  <button type="submit" class="btn btn-default">Create Player</button>
</form>-->

app/views/players/show.html.erb
<p>
  <strong>User Name:</strong>
  <%= @player.username %>
</p>
 
<p>
  <strong>Name:</strong>
  <%= @player.firstname %> <%= @player.lastname %> 
</p>