config/routes.rb
FoosballApp::Application.routes.draw do
  devise_for :players

  resources :players
  resources :games do
    post :generate_teams, on: :new
    post :player_dropdown, on: :new
    post :add_player, on: :new
    post :remove_player, on: :new
    post :setup_submit, on: :new
    member do 
      post :undo
      post :rematch
    end
    
  end

  resources :positions do
    member do
      post :score
    end
  end

  root 'pages#home'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="container">
  	<p class="pull-right">Designed by <strong>Scott Kraemer</strong></p>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "foos", root_path, class: "navbar-brand foos-brand" %>
    </div>


    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="<%= current_page?(root_path)? 'active' : '' %>">
          <%= link_to "Home", root_path %>
        </li>
        <li class="<%= current_page?(players_path)? 'active' : '' %>"><%= link_to "Players", players_path %>
        </li>
        <li class="<%= current_page?(games_path)? 'active' : '' %>"><%= link_to "Games", games_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if player_signed_in? %>
          <li>
            <%= link_to "Hi #{current_player.username.humanize}", edit_player_path(current_player) %>
          </li>
          <li>
            <%= link_to "Logout", destroy_player_session_path, method: :delete %>
          </li>
        <% else %>
          <li class="<%= current_page?(new_player_registration_path)? 'active' : '' %>"><%= link_to "Sign Up", new_player_registration_path %>
          </li>
          <li class="<%= current_page?(new_player_session_path)? 'active' : '' %>"><%= link_to "Login", new_player_session_path %>
          </li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title></title>
    
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <%= render "layouts/navbar" %>

    <div class="container">

      <% if notice %><div class="alert alert-info"><%= notice %></div><% end %>
      <% if alert %><div class="alert alert-warning"><%= alert %></div><% end %>
      <%= yield %>
    </div>

    <%= render "layouts/footer" %>
  </body>
</html>

app/views/layouts/pages.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title></title>
    
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <%= render "layouts/navbar" %>

    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>